AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram Bot Webhook Listener

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 512
  Entrypoint:
    Type: String
    Default: com.webhook.core

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        HL_ENTRYPOINT: !Ref Entrypoint

Resources:
  WebhookLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WebhookLambdaFunction
      PackageType: Image
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BotHttpApi
            Path: /
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

  BotHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain

Outputs:
  WebhookLambdaEndpoint:
    Description: Endpoint for WebhookLambdaFunction
    Value:
      Fn::Sub: https://${BotHttpApi}.execute-api.${AWS::Region}.amazonaws.com
